In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [37]:
dataset = pd.read_csv('CENSUS_INCOME.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [44]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:, 6:7] = imputer.fit_transform(X[:, 6:7])
X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size = 0.2, random_state=0)

In [45]:
print(X)

[[39 ' State-gov' 77516 ... 0 40 ' United-States']
 [50 ' Self-emp-not-inc' 83311 ... 0 13 ' United-States']
 [38 ' Private' 215646 ... 0 40 ' United-States']
 ...
 [58 ' Private' 151910 ... 0 40 ' United-States']
 [22 ' Private' 201490 ... 0 20 ' United-States']
 [52 ' Self-emp-inc' 287927 ... 0 40 ' United-States']]


In [46]:
print(y)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' >50K']


In [47]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:, 6:7] = imputer.fit_transform(X[:, 6:7])

In [48]:
print(X)

[[39 ' State-gov' 77516 ... 0 40 ' United-States']
 [50 ' Self-emp-not-inc' 83311 ... 0 13 ' United-States']
 [38 ' Private' 215646 ... 0 40 ' United-States']
 ...
 [58 ' Private' 151910 ... 0 40 ' United-States']
 [22 ' Private' 201490 ... 0 20 ' United-States']
 [52 ' Self-emp-inc' 287927 ... 0 40 ' United-States']]


In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [1, 3, 5, 6, 7, 8, 9, 10])],
                       remainder='passthrough')
X = np.array(X)

In [52]:
X = ct.fit_transform(X)

In [54]:
print(X)

[[0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 13 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 ...
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 20 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']]


In [55]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
le = LabelEncoder()
y = le.fit_transform(y)

In [56]:
print(y)

[0 0 0 ... 0 0 1]


In [57]:
X = np.asarray(X)
y = np.asarray(y)

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size = 0.2, random_state=0)

In [59]:
print(X_train)

[[0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 54 ' United-States']
 [0.0 0.0 0.0 ... 0 50 ' United-States']
 ...
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 1.0 ... 0 45 ' United-States']
 [0.0 0.0 0.0 ... 0 48 ' United-States']]


In [60]:
print(X_test)

[[0.0 0.0 0.0 ... 0 44 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 ...
 [0.0 0.0 0.0 ... 0 60 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 50 ' United-States']]


In [61]:
print(y_train)

[0 0 0 ... 0 1 0]


In [62]:
print(y_test)

[0 0 0 ... 1 0 1]


In [72]:
X_train = np.array(X_train)
X_test = np.array(X_test)

In [79]:
sc = StandardScaler()

In [82]:
print(X_train)

[[0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 54 ' United-States']
 [0.0 0.0 0.0 ... 0 50 ' United-States']
 ...
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 1.0 ... 0 45 ' United-States']
 [0.0 0.0 0.0 ... 0 48 ' United-States']]


In [83]:
print(X_test)

[[0.0 0.0 0.0 ... 0 44 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 ...
 [0.0 0.0 0.0 ... 0 60 ' United-States']
 [0.0 0.0 0.0 ... 0 40 ' United-States']
 [0.0 0.0 0.0 ... 0 50 ' United-States']]
